m1:
  image: mongo
  command: mongod --replSet "rs0" --port 27017
  hostname: mongo1
  labels:
    - global.clustering.type=mongo
    - global.clustering.mongo=primary
  environment:
    - host_config=m2:mongo2,tp:mongo3
  restart: on-failure

m2:
  image: mongo
  command: mongod --replSet "rs0" --port 27018
  hostname: mongo2
  labels:
    - global.clustering.type=mongo
    - global.clustering.mongo=secondary
  environment:
    - host_config=m1:mongo1,tp:mongo3
  restart: on-failure

m3:
  image: mongo
  command: mongod --replSet "rs0" --port 27019
  hostname: mongo3
  ports:
    - "27019:27019"
  labels:
    - global.clustering.type=mongo
    - global.clustering.mongo=secondary
  environment:
    - host_config=tp:mongo1,tp:mongo2
  restart: on-failure

tp:
  image: shopify/toxiproxy
  ports:
    - "8474:8474"
    - "27017:27017"
    - "27018:27018"
  labels:
    - global.clustering.type=toxi
  environment:
    - tp_config=m1:27017,m2:27018,m3:27019
  restart: on-failure
