version: "2"

services:
  m1:
    image: mongo
    command: mongod --replSet "rs0" --port 27017
    restart: on-failure
    networks:
      dc1:
        aliases:
          - mongo1

  m2:
    image: mongo
    command: mongod --replSet "rs0" --port 27018
    restart: on-failure
    networks:
      dc1:
        aliases:
          - mongo2

  m3:
    image: mongo
    command: mongod --replSet "rs0" --port 27019
    restart: on-failure
    networks:
      dc2:
        aliases:
          - mongo3

  tp:
    image: shopify/toxiproxy
    ports:
      - "8474:8474"
      - "27017:27017"
      - "27018:27018"
      - "27019:27019"
    labels:
      - global.clustering.type=toxi
    environment:
      - tp_config=m1:27017,m2:27018,m3:27019
    restart: on-failure
    networks:
      dc1:
        aliases:
          - mongo3
      dc2:
        aliases:
          - mongo1
          - mongo2

networks:
  dc1:
  dc2:
