version: "2"

services:
  m1:
    image: mongo
    command: mongod --replSet "rs0" --port 27017
    restart: on-failure
    networks:
      dc1:
        aliases:
          - mongo1
    labels:
      - 'global.clustering.type=mongo'

  m2:
    image: mongo
    command: mongod --replSet "rs0" --port 27018
    restart: on-failure
    networks:
      dc1:
        aliases:
          - mongo2
    labels:
      - 'global.clustering.type=mongo'

  m3:
    image: mongo
    ports:
      - "27019:27019"
    command: mongod --replSet "rs0" --port 27019
    restart: on-failure
    networks:
      dc2:
        aliases:
          - mongo3
    labels:
      - 'global.clustering.type=mongo'

  tp:
    image: shopify/toxiproxy
    ports:
      - "8474:8474"
      - "27017:27017"
      - "27018:27018"
    restart: on-failure
    networks:
      dc1:
        aliases:
          - mongo3
      dc2:
        aliases:
          - mongo1
          - mongo2
      priv:
        aliases:
          - tp

  init:
    build: ./init
    environment:
      - tp_config=m1:27017,m2:27018,m3:27019
    networks:
      - priv
    depends_on:
      - m1
      - m2
      - m3
      - tp

networks:
  dc1:
  dc2:
  priv:
